CREATE TYPE cart_status AS ENUM ('CREATED', 'INACTIVE', 'PAYMENT_MADE');

CREATE TABLE TB_PRODUCT (
    ID SERIAL PRIMARY KEY,
    PRODUCT_NAME VARCHAR(255) NOT NULL
);

CREATE TABLE TB_CART (
    ID SERIAL PRIMARY KEY,
    CLIENT_EMAIL VARCHAR(255) NOT NULL,
    STATUS cart_status NOT NULL,
    UPDATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE TB_CART_PRODUCT (
    CART_ID INTEGER NOT NULL,
    PRODUCT_ID INTEGER NOT NULL,
    PRODUCT_QUANTITY INTEGER NOT NULL,
    PRIMARY KEY (CART_ID, PRODUCT_ID),
    FOREIGN KEY (CART_ID) REFERENCES TB_CART(ID),
    FOREIGN KEY (PRODUCT_ID) REFERENCES TB_PRODUCT(ID)
);

CREATE INDEX idx_cart_status ON TB_CART(STATUS);
CREATE INDEX idx_cart_updated_at ON TB_CART(UPDATED_AT);
CREATE INDEX idx_cart_product_cart_id ON TB_CART_PRODUCT(CART_ID);
CREATE INDEX idx_cart_product_product_id ON TB_CART_PRODUCT(PRODUCT_ID);
